# Generated by Django 3.0.6 on 2020-11-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.CharField(max_length=1200, null=True),
        ),
    ]
