# Generated by Django 3.0.6 on 2020-11-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_album_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=50)),
                ('lyricists', models.CharField(max_length=50)),
                ('composer', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=1200, null=True)),
            ],
        ),
    ]
