# Generated by Django 3.0.6 on 2020-11-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_url',
            field=models.CharField(max_length=1200, null=True),
        ),
    ]
