# Generated by Django 3.0.6 on 2020-11-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_song_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
        migrations.AddField(
            model_name='album',
            name='director',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
